### ISSUE TITLE
combining coco datasets with different category list

### ISSUE THREAD

**Issue by fcakyon** [ashnair1/COCO-Assistant#16]
I am wondering what happens when I want to merge two coco sets having different category list in their respective "categories" fields. Can COCO-Assistant handle that scenario?

Bests

**Comment by ashnair1** [comment]
At the moment, no. But I'll be looking into this.

**Comment by ashnair1** [comment]
Added in 217880fcd447e19f30b0607a4c8c768f5e1ab8c3

**Comment by fcakyon** [comment]
Thanks a lot
