### ISSUE TITLE
merging dataset

### ISSUE THREAD

**Issue by xkzy** [ashnair1/COCO-Assistant#17]
![image](https://user-images.githubusercontent.com/25977542/83763691-30649680-a6a3-11ea-9269-9df26baa2d25.png)
i don't know what happen when i try to merge datasets together.

**Comment by ashnair1** [comment]
Do the datasets have the same category list? Currently, COCO-Assistant expects the datasets to have the same category listing.

**Comment by ashnair1** [comment]
Closed due to inactivity. Try with the latest version and reopen if you still face this issue.
