### ISSUE TITLE
Error with visualization

### ISSUE THREAD

**Issue by Shravan1804** [ashnair1/COCO-Assistant#22]
Hi,
Thanks for your library, it is very useful.
When trying the visualization mode, I get the following error:

> Traceback (most recent call last):
>   File ".../site-packages/matplotlib/cbook/__init__.py", line 216, in process
>     func(*args, **kwargs)
>   File ".../site-packages/matplotlib/widgets.py", line 220, in _release
>     func(event)
>   File ".../site-packages/coco_assistant/coco_visualiser.py", line 79, in forward
>     self.set_val(i)
>   File ".../site-packages/matplotlib/widgets.py", line 466, in set_val
>     func(val)
>   File ".../site-packages/coco_assistant/coco_visualiser.py", line 153, in update
>     ann.showAnns(img_anns, ax=ax)
> TypeError: showAnns() got an unexpected keyword argument 'ax'
> Traceback (most recent call last):
>   File ".../site-packages/matplotlib/cbook/__init__.py", line 216, in process
>     func(*args, **kwargs)
>   File ".../site-packages/matplotlib/widgets.py", line 220, in _release
>     func(event)
>   File ".../site-packages/coco_assistant/coco_visualiser.py", line 79, in forward
>     self.set_val(i)
>   File ".../site-packages/matplotlib/widgets.py", line 466, in set_val
>     func(val)
>   File ".../site-packages/coco_assistant/coco_visualiser.py", line 153, in update
>     ann.showAnns(img_anns, ax=ax)
> TypeError: showAnns() got an unexpected keyword argument 'ax'
> Traceback (most recent call last):
>   File ".../site-packages/matplotlib/cbook/__init__.py", line 216, in process
>     func(*args, **kwargs)
>   File ".../site-packages/matplotlib/widgets.py", line 220, in _release
>     func(event)
>   File ".../site-packages/coco_assistant/coco_visualiser.py", line 79, in forward
>     self.set_val(i)
>   File ".../site-packages/matplotlib/widgets.py", line 466, in set_val
>     func(val)
>   File ".../site-packages/coco_assistant/coco_visualiser.py", line 153, in update
>     ann.showAnns(img_anns, ax=ax)
> TypeError: showAnns() got an unexpected keyword argument 'ax'

Thanks

**Comment by Shravan1804** [comment]
Found a fix: extend COCO class and redefine the showAnns method to accept the ax parameter. Remove ax = plt.gca()

**Comment by ashnair1** [comment]
COCO Assistant actually uses a custom fork of the pycocotools library as you can see in the requirements.txt. The `showAnns` function in the fork has been modified to accept ax.
