### ISSUE TITLE
Merging two sets (training, validation) of the same coco-format dataset, with segmentation is in RLE

### ISSUE THREAD

**Issue by edwardnguyen1705** [ashnair1/COCO-Assistant#23]
Hi @ashnair1 , 
Thanks for sharing.
Does this code work for merging two sets (training, validation) of the same dataset, with segmentation is in RLE?

**Comment by ashnair1** [comment]
Yes. As long as your directory is as specified in the README.md, merging should work.

**Comment by edwardnguyen1705** [comment]
Hi @ashnair1 ,
Thank you. I have successfully merged two sets into one.
