### ISSUE TITLE
AssertionError: Annotation ids are not unique!

### ISSUE THREAD

**Issue by reubenwenisch** [ashnair1/COCO-Assistant#24]
I tried merging 3 JSON files using the coco-assistant and when using on my training code ran through this error. How do I ensure the annotation ids are different when merging?

**Comment by ashnair1** [comment]
Did you install coco-assistant from source or from pypi?

**Comment by ashnair1** [comment]
Closed due to inactivity. Try with the latest version and reopen if you still face this issue.

**Comment by AdnanMunir294** [comment]
AssertionError: Annotation ids in '/content/test/img/coco128.json' are not unique
I need help please
