### ISSUE TITLE
Crop image but still mapping annotation

### ISSUE THREAD

**Issue by winter2897** [ashnair1/COCO-Assistant#33]
Hi @ashnair1 ,
I want to crop the large image into several small images and retain the annotation mapping. Can you give me advice?
![a](https://user-images.githubusercontent.com/22476495/111749060-e06a5f80-88c3-11eb-9013-951d6a126dea.png)

**Comment by ashnair1** [comment]
I'm not sure what you mean by annotation mapping. Is the annotation made at the large image level? So for example, you have one large image and one annotation file and you want to know how to tile it?

**Comment by winter2897** [comment]
I already have the label file of the large image. I want it when I cut it into small pictures. These snapshots are automatically labeled in the COCO format. @ashnair1

**Comment by ashnair1** [comment]
What format is the label file? 

It seems you're working on geospatial imagery so I'm assuming your image is a GeoTIFF and label file is a GeoJSON/Shapefile. Is that correct?

**Comment by winter2897** [comment]
I'm working on large image sizes of solar panels. I label them with `labelme` and then use the code `labelme2coco.py`
![Screenshot from 2021-03-19 17-37-22](https://user-images.githubusercontent.com/22476495/111767865-cb003000-88d9-11eb-92ba-57ebdc672825.png)
 to convert the `.json` files to COCO format which is a single file` train.json`.

**Comment by winter2897** [comment]
Since the size image is too large, I want to cut it into small sheets. These small photos, after being cut, must automatically be labeled in the `COCO format`.

**Comment by ashnair1** [comment]
Since this is not really an issue about the COCO-Assistant library itself, I'll be moving this issue to Discussions.
