### ISSUE TITLE
JPEG images are not merged while merging different coco dataset

### ISSUE THREAD

**Issue by yogeshkumarpilli** [ashnair1/COCO-Assistant#48]
Hello 

Thank you for your amazing work.

I have checked [issue20](https://github.com/ashnair1/COCO-Assistant/issues/20)

I have noticed the below code where you give png, jpg, and jpeg  in coco_assistant.py is been updated
   ```
 if merge_images:
            print("Merging image dirs")
            im_dirs = self.imgfolders
            imext = [".png", ".jpg", ".jpeg"]

```

I have tried installing the coco_assistant using
  ```
pip install coco-assistant
  ```

```
import os
from coco_assistant import COCO_Assistant

# Specify image and annotation directories
img_dir = os.path.join(os.getcwd(), 'images')
ann_dir = os.path.join(os.getcwd(), 'annot')

# Create COCO_Assistant object
# cas = COCO_Assistant(img_dir, ann_dir)
cas = COCO_Assistant(img_dir, ann_dir)
cas.merge(merge_images=True)
```

My dataset is having JPEG and JPG images. 
While Doing this I can merge JPG images but not JPEG in merged images
but in annotations this JPEG file is present.

I do not know why.
Can you give any insights? It will be very helpful

**Comment by ashnair1** [comment]
The inclusion of `.jpeg` extension was done after the release of v0.3.4 which is the version currently on PyPI. So if you want this feature you can install coco assistant from source as mentioned [here](https://github.com/ashnair1/COCO-Assistant#2-installation-from-source). 

I'm planning to push a new release (v0.3.5) soon so this issue should be resolved by then

**Comment by yogeshkumarpilli** [comment]
I have installed it from the source file. 
It is working perfectly. I hope the new version will be coming soon.
Thank you again for your help!
I am closing this issue.

**Comment by ashnair1** [comment]
New version released
