### ISSUE TITLE
Hi, how can I merge it for multiple dataset??

### ISSUE THREAD

**Issue by Nurungyi** [ashnair1/COCO-Assistant#53]
Hi, I am trying to merge the multiple images with coco json format.
And, I could find your github page seems like very nice.

My question is that I have a dataset. and each image with each json file (coco format).
In this case, how can I use your set (an example is below?
If a picture or video such as youtube for easily understanding your nice code exists, it will be better.

Thank you.

    images
          -abc1.tiff
          -abc2.tiff
          -abc3.tiff
          -abc4.tiff

    annotations
          -abc1.json
          -abc2.json
          -abc3.json
          -abc4.json

**Comment by ashnair1** [comment]
Hi @Nurungyi.  A coco dataset consists of multiple images and **one** annotation file. In your case, it would be something like this:

```
images
      -abc1.tiff
      -abc2.tiff
      -abc3.tiff
      -abc4.tiff

annotations
      abc.json

``` 

The abc.json should contain annotations for all the images. You can refer the [MS-COCO data format](https://cocodataset.org/#format-data) for more details.

**Comment by Nurungyi** [comment]
I could merge my dataset using your library even if I added something to a code. As you said, generally a dataset consists for many image files with  one coco json format. However, I got a dataset which has one image with one json. Anyway I am sure that you made a very useful tool. Many thanks again :)

**Comment by ashnair1** [comment]
Were you able to solve the problem?

**Comment by Nurungyi** [comment]
Yes. I made each folder for each image. As a result, one folder has one image. I put all json files for each image in one folder. And then, I used your library. It worked for me. Many thanks,

**Comment by ashnair1** [comment]
Great to hear
