### ISSUE TITLE
How should we use this package??

### ISSUE THREAD

**Issue by masouduut94** [ashnair1/COCO-Assistant#55]
I have multiple directories and in each directory there exists a dataset with coco format.
I just found this package but I do not have any tutorial on how to use it?

can u please help me guys?

**Comment by ashnair1** [comment]
You can refer the documentation [here](https://ashnair1.github.io/COCO-Assistant/usage/)

**Comment by masouduut94** [comment]
Oh, Thank you, man. Please mention the provided link into the readme file. It can help a lot of developers.

**Comment by ashnair1** [comment]
Yeah. I added the docs later and must have forgotten to add the link. Fixed now.

**Comment by ashnair1** [comment]
Closing this issue. Feel free to open a new one if you encounter a bug. Cheers!
