### ISSUE TITLE
TypeError: merge() got an unexpected keyword argument 'merge_images'

### ISSUE THREAD

**Issue by rahulsharma11** [ashnair1/COCO-Assistant#58]
Hi, when i run merge command, "cas.merge(merge_images=True) ",
i got the error- 
TypeError: merge() got an unexpected keyword argument 'merge_images'

Any suggestions?
Thanks.

**Comment by ashnair1** [comment]
The merge_images argument was removed in 0.4.0 since merge images would basically involve copying the two image folders and put them together.

You can just run `cas.merge()` to merge the annotations. I'll update the documentation.

**Comment by rahulsharma11** [comment]
Thanks
