### ISSUE TITLE
Throwing error while Generate pie-chart that shows distribution of objects according to their size (as specified in areaRng).

### ISSUE THREAD

**Issue by MLDeep414** [ashnair1/COCO-Assistant#59]
@ashnair1 ashnair1

![coco assistant issue](https://user-images.githubusercontent.com/88261995/148677355-c255fae1-c352-44f1-8964-a2622ee8a97e.JPG)
I am using Google colab, while using 

>>> cas.ann_stats(stat="cat", arearng=None, show_count=False, save=False)

arearng=None, I did not understand what should be the arearng, I want complete distribution of categories from my COCO json file.
Please Help, Thanks.

**Comment by ashnair1** [comment]
You'll need to provide the full stack trace and the version of coco-assistant you're using. Most of the time these issues are caused by the data not being in the right format. 

Try running the funtion on this dataset -> https://github.com/ashnair1/tiny_coco

It's working on my end with the latest version (0.4.0)

![cas](https://user-images.githubusercontent.com/32295036/148678129-83eedde7-4bb0-4a1b-a654-aca1a7197e5a.png)

**Comment by MLDeep414** [comment]
Hi,


when I use >>> cas = COCO_Assistant(img_dir, ann_dir)
This does not show loading annotations....etc.

I am not getting where it is going wrong.

Can you please check for this sample one image, I even tried with my
dataset but this is not working, can you please help.

Thanks.

**Comment by ashnair1** [comment]
The command is `cas = COCO_Assistant(img_dir, ann_dir)`. You don't need `>>>`. Refer the image I attached on how to use the command.

**Comment by MLDeep414** [comment]
I have used that before, as I am not getting again I used >>> cas

I am using coco assistant 0.4.0

What is the meaning of Number of columns must be positive integer?

And at arearng- area range when there are many images what should I write
over there?


Thanks,
Deepthi-P

**Comment by MLDeep414** [comment]
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/COCO_ASS')
print(os.getcwd())

!pip install --upgrade numpy

! pip install coco-assistant

!git clone https://github.com/ashnair1/COCO-Assistant.git

%cd COCO-Assistant/
!pip install .

os.chdir('/content/drive/MyDrive/COCO_ASS/COCO-Assistant')


from coco_assistant import COCO_Assistant
import os
# Specify image and annotation directories
img_dir = os.path.join(os.getcwd(), 'deep', 'images' )
ann_dir = os.path.join(os.getcwd(), 'deep', 'annotations')

# Create COCO_Assistant object
cas = COCO_Assistant(img_dir, ann_dir)

cas.ann_stats(stat="cat", arearng=[1368], show_count=True, save=False)

This is how I am doing, Please correct me if I am wrong.

Thanks,
Deepthi-P

**Comment by ashnair1** [comment]
I don't think you're pointing to the data correctly. According to this script your img_dir and ann_dir are pointing to `/content/drive/MyDrive/COCO_ASS/COCO-Assistant/deep/images` and `/content/drive/MyDrive/COCO_ASS/COCO-Assistant/deep/annotations` respectively.

**Comment by MLDeep414** [comment]
Can you help me, how to do this? Please.

**Comment by ashnair1** [comment]
Without steps to reproduce your errors I cannot help you. 

Try to do the following:

1. `git clone https://github.com/ashnair1/tiny_coco.git`
2. Open jupyter notebook 
3. Copy the code from the image I attached earlier

**Comment by MLDeep414** [comment]
I am using Google colab can we do in this??

**Comment by ashnair1** [comment]
Yes

**Comment by ashnair1** [comment]
It works on colab as well. I feel your errors are due to your data.

![image](https://user-images.githubusercontent.com/32295036/148683313-241261a6-83fa-4dd6-bf34-13892cc480fc.png)

![image](https://user-images.githubusercontent.com/32295036/148683349-cb57cdb7-26c7-44eb-b57b-820dde706a25.png)

**Comment by MLDeep414** [comment]
Yes, it is working with tiny_coco.git,
Ok Thank You

**Comment by MLDeep414** [comment]
Hi,
This is working fine with tiny_coco.git, I have one more question, is there
any possibility that  instead of getting plot,can we get the name of the
category and the distribution of instances like a chart.

Thanks.

**Comment by ashnair1** [comment]
What do you mean by distribution of instances? Can you give an example?

**Comment by MLDeep414** [comment]
![instances chart](https://user-images.githubusercontent.com/88261995/148723562-8d7e30d6-740b-449c-8677-9f623f032466.JPG)
I have attached image in mail.

**Comment by ashnair1** [comment]
Currently this is not supported. If I have time, I'll add this in the next version.

**Comment by MLDeep414** [comment]
ok, Thank You
