### ISSUE TITLE
give list of classes to remove

### ISSUE THREAD

**Issue by TBondat** [ashnair1/COCO-Assistant#9]
hi,
you have done a very useful tool. it would be very good to provide directly the list of classes to remove at once, like
['car','boat'] instead of manual loop. 

or on the opposite, if we could provide just the list of classes we want to keep. would be very useful!

**Comment by ashnair1** [comment]
I've updated the category removal function to now accept a list of categories as input.

**Comment by TBondat** [comment]
awesome! thanks for the quick update :)
